name: Release to VSCode Marketplace

on:
  release:
    types:
      - published
      - prereleased
jobs:
  publish:
    name: Release to VSCode Marketplace
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Publish official version
        if: success()
        run: bunx release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
